### ISSUE TITLE
LDM-4 on ImageNet 256× 256 results

### ISSUE THREAD

**Issue by myWonderfulPig** [Xingyu-Zheng/BinaryDM#1]
Hi, Thanks for the wonderful job. I am finding your provided imagenet 256× 256 results differ from that of LDM-4 paper.

Your results in paper:
<img width="481" alt="image" src="https://github.com/Xingyu-Zheng/BinaryDM/assets/169539911/461310ad-a911-4172-886a-ceae905dae4a">

LDM-4:
<img width="1204" alt="image" src="https://github.com/Xingyu-Zheng/BinaryDM/assets/169539911/4196a78e-7fa2-4afa-9a7e-8a7d5dea6d85">

You can see that the IS score is especially odd. 

Also, I am wondering why on this benchmark your FID is better than FP. In other benchmarks there is no such a phenomenon.

Thanks!

**Comment by Xingyu-Zheng** [comment]
Thank you for your attention to our work!

Actually, we encountered similar issues in our research as well. For instance, here are the results from [EfficientDM [ICLR 2024]](https://arxiv.org/pdf/2310.03270):
![image](https://github.com/Xingyu-Zheng/BinaryDM/assets/95268836/26459740-2d29-47b3-9722-4f6fa519530d)

These are the results from [TFMQ-DM [CVPR 2024]](https://arxiv.org/abs/2311.16503):
![image](https://github.com/Xingyu-Zheng/BinaryDM/assets/95268836/577ac869-2632-4c81-9542-1830f3ceca72)

Overall, we observed three prominent features in the test results:

- IS/FID of FP models are inconsistent.
- The IS of quantized models does not surpass that of FP models.
- The FID of quantized models may be lower than that of FP models.

To ensure a fair comparison, we conducted evaluations on BinaryDM using our custom-built pipeline, specifically:

- DDIM (20 steps).
- We generated 10 images for each of the 1000 classes in Imagenet.
- Send the npz file containing 10,000 images to [evaluations](https://github.com/openai/guided-diffusion/tree/main/evaluations).

It's worth mentioning that, from our visual perception:

- Using IS to evaluate the quality of generated images on Imagenet is closer to the actual level of them.
- FID seems to be more suitable for datasets like LSUN-Bedrooms, LSUN-Churches, FFHQ, etc.

We hope these findings are helpful to you!

**Comment by myWonderfulPig** [comment]
Thanks very much for your explanations, the findings are really exciting and helpful! :smile:
